import React from 'react';
import {
  AccessTime,
  AccountCircle,
  AddToQueue,
  Article,
  Assessment,
  Assignment,
  BarChart,
  DevicesOther,
  DisplaySettings,
  DomainAdd,
  Favorite,
  FlagCircle,
  GroupAdd,
  Groups,
  Inbox,
  Info,
  LibraryBooks,
  ListAlt,
  Lock,
  LockPerson,
  Mail,
  MonitorHeart,
  Notifications,
  Password,
  PermContactCalendar,
  PermPhoneMsg,
  Person,
  RequestQuote,
  Search,
  Settings,
  Shield,
  SwitchAccount,
  Today,
  Videocam,
} from '@mui/icons-material';
import { menuItem } from './menuInterface.ts';
import { UserMd } from '../../../assets/icons/userMd.tsx';

// Menu Items data / data structure
export const menuItems: menuItem[] = [
  {
    key: 1,
    title: 'patients',
    link: '/patients',
    icon: <Groups />,
    submenu: [
      {
        key: 'newp',
        title: 'create_a_new_patient',
        link: '',
        icon: <Person />,
      },
      {
        key: 'plist',
        title: 'patient_list',
        link: '',
        icon: <Groups />,
      },
      {
        key: 'appoint',
        title: 'appointments',
        icon: <AccessTime />,
        link: ' ',
      },
      {
        key: 'reports',
        title: 'Reports',
        icon: <Assessment />,
        link: ' ',
      },
    ],
  },
  {
    key: 2,
    title: 'Telehealth',
    link: '/telehealth',
    icon: <AddToQueue />,
    submenu: [
      {
        key: 'teledash',
        title: 'Telehealth Dashboard',
        link: '',
        icon: <AddToQueue />,
      },
      {
        key: 'teleschedule',
        title: 'schedule',
        link: '',
        icon: <PermContactCalendar />,
      },
      {
        key: 'teleappointments',
        title: 'appointments',
        link: '',
        icon: <Today />,
      },
    ],
  },
  {
    key: 3,
    title: 'remote_patient_monitoring',
    link: '/rpm',
    icon: <Favorite />,
    submenu: [
      {
        key: 'rpmdashboard',
        title: 'rpm_dashboard',
        link: '',
        icon: <Favorite />,
      },
      {
        key: 'rpmstatistics',
        title: 'rpm_statistics',
        link: '',
        icon: <MonitorHeart />,
      },
      {
        key: 'rpmeducation',
        title: 'rpm_education_list',
        link: '',
        icon: <LibraryBooks />,
      },
      {
        key: 'rpmtasks',
        title: 'tasks',
        link: '',
        icon: <Assignment />,
      },
      {
        key: 'rpmreports',
        title: 'reports',
        link: '',
        icon: <BarChart />,
      },
      {
        key: 'rpmcompliantpatients',
        title: 'compliant_patients',
        link: '',
        icon: <BarChart />,
      },
      {
        key: 'rpmimprovingbp',
        title: 'improving_bp',
        link: '',
        icon: <BarChart />,
      },
      {
        key: 'rpmclaimsapproval',
        title: 'rpm_claims_approval',
        link: '',
        icon: <RequestQuote />,
      },
      {
        key: 'rpmmedicaldevices',
        title: 'medical_devices',
        link: '',
        icon: <DevicesOther />,
      },
      {
        key: 'rpmconsentlist',
        title: 'consent_list',
        link: '',
        icon: <LibraryBooks />,
      },
    ],
  },
  {
    key: 4,
    title: 'settings',
    link: '/settings',
    icon: <Settings />,
    submenu: [
      {
        key: 'sttappointments',
        title: 'appointment_types',
        link: '',
        icon: <PermContactCalendar />,
      },
      {
        key: 'sttcareteam',
        title: 'care_team',
        link: '',
        icon: <UserMd />,
      },
      {
        key: 'sttconsentlist',
        title: 'consent_list',
        link: '',
        icon: <ListAlt />,
      },
      {
        key: 'sttvitals',
        title: 'vitals_reference_ranges',
        link: '',
        icon: <MonitorHeart />,
      },
      {
        key: 'sttreporttelehealth',
        title: 'report_telehealth',
        link: '',
        icon: <AddToQueue />,
      },
      {
        key: 'sttpopulationgroups',
        title: 'population_groups',
        link: '',
        icon: <Groups />,
      },
      {
        key: 'sttreferringp',
        title: 'referring_provider_list',
        link: '',
        icon: <GroupAdd />,
      },
      {
        key: 'sttgoalset',
        title: 'goal_set',
        link: '',
        icon: <FlagCircle />,
      },
      {
        key: 'sttpracticelist',
        title: 'practice_list',
        link: '',
        icon: <Article />,
      },
      {
        key: 'sttfeeschedule',
        title: 'fee_schedule',
        link: '',
        icon: <Article />,
      },
      {
        key: 'sttinsurancelist',
        title: 'insurances_list',
        link: '',
        icon: <Article />,
      },
      {
        key: 'sttvoicecalls',
        title: 'voice_calls_report',
        link: '',
        icon: <PermPhoneMsg />,
      },
      {
        key: 'sttnewprovider',
        title: 'new_provider',
        link: '',
        icon: <DomainAdd />,
      },
      {
        key: 'sttinteroperabilitysettings',
        title: 'interoperability_settings',
        link: '',
        icon: <DisplaySettings />,
      },
      {
        key: 'sttadminusers',
        title: 'admin_users',
        link: '',
        icon: <LockPerson />,
      },
      {
        key: 'sttanalyticsapi',
        title: 'analytics_api_calls',
        link: '',
        icon: <BarChart />,
      },
      {
        key: 'sttreportsinbox',
        title: 'reports_inbox',
        link: '',
        icon: <Inbox />,
      },
      {
        key: 'sttreportsdashboard',
        title: 'reports_dashboard',
        link: '',
        icon: <Assessment />,
      },
    ],
  },
  {
    key: 5,
    title: 'telehealth',
    link: '/waiting-room',
    icon: <Videocam />,
    submenu: [],
  },
];

export const bottomMenuItems: menuItem[] = [
  {
    key: 6,
    title: 'search',
    link: '#search',
    icon: <Search />,
    submenu: [],
  },
  {
    key: 7,
    title: 'messages',
    link: '/inbox',
    icon: <Mail />,
    submenu: [],
  },
  {
    key: 8,
    title: 'notifications',
    link: '/notifications',
    icon: <Notifications />,
    submenu: [],
  },
  {
    key: 9,
    title: 'user',
    link: '/user',
    icon: <AccountCircle />,
    submenu: [
      {
        key: 'profile',
        title: 'profile',
        link: '',
        icon: <Person />,
      },
      {
        key: 'secquestions',
        title: 'security_questions',
        link: '',
        icon: <Shield />,
      },
      {
        key: 'pass',
        title: 'password',
        link: '',
        icon: <Password />,
      },
      {
        key: 'medicaldevices',
        title: 'medical_devices',
        link: '',
        icon: <DevicesOther />,
      },
      {
        key: 'aboutus',
        title: 'about_us',
        link: '',
        icon: <Info />,
      },
      {
        key: 'changeaccount',
        title: 'change_account',
        link: '',
        icon: <SwitchAccount />,
      },
      {
        key: 'logout',
        title: 'log_out',
        link: '',
        icon: <Lock />,
      },
    ],
  },
];
