// Api for alerts tab at Lateral Menu:
// http://localhost/api/comments/comment/?type=6&is_read=false
import { NotificationsProps } from '../dto/Notifications';

export const NOTIFICATIONS_DATA = {
  total: 4,
  data: [
    {
      id: 4,
      documents: [],
      patient_name: 'Joyce Smither',
      need_action_by: [],
      user_data: {
        id: 298,
        full_name: 'esvyda super system user',
      },
      comment:
        'CCM verbal consent form of the patient Joyce signed by user 14 at 2024-08-12 18:50:15.265997',
      action_id: null,
      created_at: '2024-08-12T13:50:15.272685-05:00',
      updated_at: null,
      relation_id: 20,
      subject:
        'Patient Joyce signed the consent form for RPM at 2024-08-12 18:50:15.266013',
      needaction: null,
      need_moderation: null,
      record_name: 'New Informed Consent CCM',
      starred: false,
      status: null,
      moderation_status: null,
      is_read: false,
      reason_comment: null,
      user: 298,
      type: 6,
      patient: 3,
      updated_by: null,
      comment_subtype: 40,
      related_model: 226,
      parent_comment: null,
      moderated_by: [],
      partner_ids: [],
      starred_partner_ids: [],
    },
    {
      id: 3,
      documents: [],
      patient_name: 'Ismael Barrios',
      need_action_by: [],
      user_data: {
        id: 298,
        full_name: 'esvyda super system user',
      },
      comment:
        'CCM verbal consent form of the patient Ismael signed by user 14 at 2024-06-24 15:23:55.980297',
      action_id: null,
      created_at: '2024-06-24T10:23:55.994209-05:00',
      updated_at: null,
      relation_id: 19,
      subject:
        'Patient Ismael signed the consent form for RPM at 2024-06-24 15:23:55.980463',
      needaction: null,
      need_moderation: null,
      record_name: 'New Informed Consent CCM',
      starred: false,
      status: null,
      moderation_status: null,
      is_read: false,
      reason_comment: null,
      user: 298,
      type: 6,
      patient: 84,
      updated_by: null,
      comment_subtype: 40,
      related_model: 226,
      parent_comment: null,
      moderated_by: [],
      partner_ids: [],
      starred_partner_ids: [],
    },
    {
      id: 2,
      documents: [],
      patient_name: 'Romulo Lozano',
      need_action_by: [],
      user_data: {
        id: 298,
        full_name: 'esvyda super system user',
      },
      comment:
        'CCM verbal consent form of the patient Romulo signed by user 14 at 2024-06-19 20:52:05.915202',
      action_id: null,
      created_at: '2024-06-19T15:52:05.930898-05:00',
      updated_at: null,
      relation_id: 18,
      subject:
        'Patient Romulo signed the consent form for RPM at 2024-06-19 20:52:05.915210',
      needaction: null,
      need_moderation: null,
      record_name: 'New Informed Consent CCM',
      starred: false,
      status: null,
      moderation_status: null,
      is_read: false,
      reason_comment: null,
      user: 298,
      type: 6,
      patient: 91,
      updated_by: null,
      comment_subtype: 40,
      related_model: 226,
      parent_comment: null,
      moderated_by: [],
      partner_ids: [],
      starred_partner_ids: [],
    },
    {
      id: 1,
      documents: [],
      patient_name: 'Ford Alex',
      need_action_by: [],
      user_data: {
        id: 298,
        full_name: 'esvyda super system user',
      },
      comment:
        'CCM verbal consent form of the patient Ford signed by user 14 at 2024-06-19 16:47:27.386039',
      action_id: null,
      created_at: '2024-06-19T11:47:27.391758-05:00',
      updated_at: null,
      relation_id: 17,
      subject:
        'Patient Ford signed the consent form for RPM at 2024-06-19 16:47:27.386045',
      needaction: null,
      need_moderation: null,
      record_name: 'New Informed Consent CCM',
      starred: false,
      status: null,
      moderation_status: null,
      is_read: false,
      reason_comment: null,
      user: 298,
      type: 6,
      patient: 60,
      updated_by: null,
      comment_subtype: 40,
      related_model: 226,
      parent_comment: null,
      moderated_by: [],
      partner_ids: [],
      starred_partner_ids: [],
    },
  ],
};

export default function NotificationsAdapter(data: NotificationsProps) {
  const notificationsData = data;
  return {
    total: notificationsData.total,
    events: notificationsData.data.map((item) => ({
      id: item.id,
      createDate: item.created_at,
      status: item.is_read,
      notificationName: item.record_name,
      comment: item.comment,
      patientId: item.patient,
      patientName: item.patient_name,
    })),
  };
}
