// Api for Inbox Section at Lateral Menu:
//esvyda-events-api-eventlist&is_read_by_medical_staff=false&only_my_patients=true&page=1&page_size=5

export const dataAux = {
  total_events: 3603,
  events: [
    {
      id: 11048,
      category: {
        id: 5,
        name: 'Symptoms Report',
        name_es: 'Reporte de sintomas',
        description: 'Patient Symptoms report',
        description_es: 'Reportes para pacientes con sintomas',
      },
      patient: {
        id: 3,
        id_people: {
          id: 4,
          first_name: 'Joyce',
          last_name: 'Smither',
          date_of_birth: null,
          age: 32,
          gender: 'F',
          image: null,
          image_filename: null,
          email: 'mmralzate7@gmail.com',
          id_user: 8,
          cell_phone: '3136013550',
        },
      },
      prescription: null,
      normal_ranges: null,
      vital_sign: null,
      symptom_resport: {
        id: 6,
        symptoms: {
          id: 21,
          name: 'cizziness',
          description: 'finding',
          laterality: null,
          notification_warning: null,
          snomedct: '404640003',
          health_service: [5, 4],
        },
        accompained_by: [
          {
            id: 24,
            name: 'flu',
            description: 'disorder',
            laterality: null,
            notification_warning: null,
            snomedct: '6142004',
            health_service: [5, 4],
          },
        ],
        pain_location: {
          id: 1,
          name: 'Around one eye or radiates one eye',
        },
        medications_related: [
          {
            id: 3,
            medication: {
              id: 13,
              name: 'aspirin',
            },
            prescribed_by: null,
            created_at: '2023-05-30T18:48:37.664396-05:00',
            updated_at: '2023-05-30T18:48:37.664397-05:00',
            medical_problems: [
              {
                id: 231,
                name_keyword: null,
              },
            ],
            status: 'A',
            providernote: 'asdsdfsdf',
            ordering_mode: '',
            earliestfilldate: null,
            refills_allowed: false,
            refills_quantity: null,
            ordering_quantity_value: null,
            with_reminder: false,
            ordering_quantity_unit: null,
            signetur: ' 2   by  route  for 23 WEEKS',
            goal: null,
          },
          {
            id: 1,
            medication: {
              id: 1,
              name: 'TylenoL',
            },
            prescribed_by: null,
            created_at: '2023-05-30T18:46:57.773307-05:00',
            updated_at: '2023-05-30T18:46:57.880717-05:00',
            medical_problems: [
              {
                id: 220,
                name_keyword: 'Radiant heat burn of skin',
              },
              {
                id: 261,
                name_keyword: null,
              },
            ],
            status: 'A',
            providernote: 'notes',
            ordering_mode: '',
            earliestfilldate: null,
            refills_allowed: false,
            refills_quantity: null,
            ordering_quantity_value: null,
            with_reminder: false,
            ordering_quantity_unit: null,
            signetur: ' 2   by  route  for 30 DAYS',
            goal: {
              id: 110,
              custom_title: null,
            },
          },
        ],
        created_at: '2023-06-08T11:17:57.137101-05:00',
        updated_at: '2023-06-20T16:04:49.119965-05:00',
        source: 'WEB',
        drug_effect_yn: true,
        pain_severity: 2,
        symptom_duration: 'everyday',
        reported_by_patient: false,
        patient_note: null,
        clinical_note: 'help',
        patient: 3,
        created_by: 6,
        updated_by: null,
      },
      cause: 'cizziness',
      cause_es: null,
      datetime_reading: '2023-06-08T16:27:11.297133-05:00',
      datetime_trigger_alert: '2023-06-08T16:27:11.297126-05:00',
      status: 'new',
      is_reviewed: false,
      is_read_by_patient: false,
      is_read_by_medical_staff: false,
      datetime_read_by_patient: '2023-06-08T16:27:11.297132-05:00',
      datetime_read_by_medical_staff: '2023-06-08T16:27:11.297133-05:00',
      symptom_report_yn: true,
      user: 6,
      transaction: null,
    },
    {
      id: 11047,
      category: {
        id: 5,
        name: 'Symptoms Report',
        name_es: 'Reporte de sintomas',
        description: 'Patient Symptoms report',
        description_es: 'Reportes para pacientes con sintomas',
      },
      patient: {
        id: 3,
        id_people: {
          id: 4,
          first_name: 'Joyce',
          last_name: 'Smither',
          date_of_birth: null,
          age: 32,
          gender: 'F',
          image: null,
          image_filename: null,
          email: 'mmralzate7@gmail.com',
          id_user: 8,
          cell_phone: '3136013550',
        },
      },
      prescription: null,
      normal_ranges: null,
      vital_sign: null,
      symptom_resport: {
        id: 6,
        symptoms: {
          id: 21,
          name: 'cizziness',
          description: 'finding',
          laterality: null,
          notification_warning: null,
          snomedct: '404640003',
          health_service: [5, 4],
        },
        accompained_by: [
          {
            id: 24,
            name: 'flu',
            description: 'disorder',
            laterality: null,
            notification_warning: null,
            snomedct: '6142004',
            health_service: [5, 4],
          },
        ],
        pain_location: {
          id: 1,
          name: 'Around one eye or radiates one eye',
        },
        medications_related: [
          {
            id: 3,
            medication: {
              id: 13,
              name: 'aspirin',
            },
            prescribed_by: null,
            created_at: '2023-05-30T18:48:37.664396-05:00',
            updated_at: '2023-05-30T18:48:37.664397-05:00',
            medical_problems: [
              {
                id: 231,
                name_keyword: null,
              },
            ],
            status: 'A',
            providernote: 'asdsdfsdf',
            ordering_mode: '',
            earliestfilldate: null,
            refills_allowed: false,
            refills_quantity: null,
            ordering_quantity_value: null,
            with_reminder: false,
            ordering_quantity_unit: null,
            signetur: ' 2   by  route  for 23 WEEKS',
            goal: null,
          },
          {
            id: 1,
            medication: {
              id: 1,
              name: 'TylenoL',
            },
            prescribed_by: null,
            created_at: '2023-05-30T18:46:57.773307-05:00',
            updated_at: '2023-05-30T18:46:57.880717-05:00',
            medical_problems: [
              {
                id: 220,
                name_keyword: 'Radiant heat burn of skin',
              },
              {
                id: 261,
                name_keyword: null,
              },
            ],
            status: 'A',
            providernote: 'notes',
            ordering_mode: '',
            earliestfilldate: null,
            refills_allowed: false,
            refills_quantity: null,
            ordering_quantity_value: null,
            with_reminder: false,
            ordering_quantity_unit: null,
            signetur: ' 2   by  route  for 30 DAYS',
            goal: {
              id: 110,
              custom_title: null,
            },
          },
        ],
        created_at: '2023-06-08T11:17:57.137101-05:00',
        updated_at: '2023-06-20T16:04:49.119965-05:00',
        source: 'WEB',
        drug_effect_yn: true,
        pain_severity: 2,
        symptom_duration: 'everyday',
        reported_by_patient: false,
        patient_note: null,
        clinical_note: 'help',
        patient: 3,
        created_by: 6,
        updated_by: null,
      },
      cause: 'cizziness',
      cause_es: null,
      datetime_reading: '2023-06-08T16:27:05.836572-05:00',
      datetime_trigger_alert: '2023-06-08T16:27:05.836555-05:00',
      status: 'new',
      is_reviewed: false,
      is_read_by_patient: false,
      is_read_by_medical_staff: false,
      datetime_read_by_patient: '2023-06-08T16:27:05.836571-05:00',
      datetime_read_by_medical_staff: '2023-06-08T16:27:05.836572-05:00',
      symptom_report_yn: true,
      user: 6,
      transaction: null,
    },
    {
      id: 11046,
      category: {
        id: 5,
        name: 'Symptoms Report',
        name_es: 'Reporte de sintomas',
        description: 'Patient Symptoms report',
        description_es: 'Reportes para pacientes con sintomas',
      },
      patient: {
        id: 3,
        id_people: {
          id: 4,
          first_name: 'Joyce',
          last_name: 'Smither',
          date_of_birth: null,
          age: 32,
          gender: 'F',
          image: null,
          image_filename: null,
          email: 'mmralzate7@gmail.com',
          id_user: 8,
          cell_phone: '3136013550',
        },
      },
      prescription: null,
      normal_ranges: null,
      vital_sign: null,
      symptom_resport: {
        id: 6,
        symptoms: {
          id: 21,
          name: 'cizziness',
          description: 'finding',
          laterality: null,
          notification_warning: null,
          snomedct: '404640003',
          health_service: [5, 4],
        },
        accompained_by: [
          {
            id: 24,
            name: 'flu',
            description: 'disorder',
            laterality: null,
            notification_warning: null,
            snomedct: '6142004',
            health_service: [5, 4],
          },
        ],
        pain_location: {
          id: 1,
          name: 'Around one eye or radiates one eye',
        },
        medications_related: [
          {
            id: 3,
            medication: {
              id: 13,
              name: 'aspirin',
            },
            prescribed_by: null,
            created_at: '2023-05-30T18:48:37.664396-05:00',
            updated_at: '2023-05-30T18:48:37.664397-05:00',
            medical_problems: [
              {
                id: 231,
                name_keyword: null,
              },
            ],
            status: 'A',
            providernote: 'asdsdfsdf',
            ordering_mode: '',
            earliestfilldate: null,
            refills_allowed: false,
            refills_quantity: null,
            ordering_quantity_value: null,
            with_reminder: false,
            ordering_quantity_unit: null,
            signetur: ' 2   by  route  for 23 WEEKS',
            goal: null,
          },
          {
            id: 1,
            medication: {
              id: 1,
              name: 'TylenoL',
            },
            prescribed_by: null,
            created_at: '2023-05-30T18:46:57.773307-05:00',
            updated_at: '2023-05-30T18:46:57.880717-05:00',
            medical_problems: [
              {
                id: 220,
                name_keyword: 'Radiant heat burn of skin',
              },
              {
                id: 261,
                name_keyword: null,
              },
            ],
            status: 'A',
            providernote: 'notes',
            ordering_mode: '',
            earliestfilldate: null,
            refills_allowed: false,
            refills_quantity: null,
            ordering_quantity_value: null,
            with_reminder: false,
            ordering_quantity_unit: null,
            signetur: ' 2   by  route  for 30 DAYS',
            goal: {
              id: 110,
              custom_title: null,
            },
          },
        ],
        created_at: '2023-06-08T11:17:57.137101-05:00',
        updated_at: '2023-06-20T16:04:49.119965-05:00',
        source: 'WEB',
        drug_effect_yn: true,
        pain_severity: 2,
        symptom_duration: 'everyday',
        reported_by_patient: false,
        patient_note: null,
        clinical_note: 'help',
        patient: 3,
        created_by: 6,
        updated_by: null,
      },
      cause: 'cizziness',
      cause_es: null,
      datetime_reading: '2023-06-08T16:26:58.158018-05:00',
      datetime_trigger_alert: '2023-06-08T16:26:58.158014-05:00',
      status: 'new',
      is_reviewed: false,
      is_read_by_patient: false,
      is_read_by_medical_staff: false,
      datetime_read_by_patient: '2023-06-08T16:26:58.158018-05:00',
      datetime_read_by_medical_staff: '2023-06-08T16:26:58.158018-05:00',
      symptom_report_yn: true,
      user: 6,
      transaction: null,
    },
    {
      id: 11045,
      category: {
        id: 5,
        name: 'Symptoms Report',
        name_es: 'Reporte de sintomas',
        description: 'Patient Symptoms report',
        description_es: 'Reportes para pacientes con sintomas',
      },
      patient: {
        id: 3,
        id_people: {
          id: 4,
          first_name: 'Joyce',
          last_name: 'Smither',
          date_of_birth: null,
          age: 32,
          gender: 'F',
          image: null,
          image_filename: null,
          email: 'mmralzate7@gmail.com',
          id_user: 8,
          cell_phone: '3136013550',
        },
      },
      prescription: null,
      normal_ranges: null,
      vital_sign: null,
      symptom_resport: {
        id: 6,
        symptoms: {
          id: 21,
          name: 'cizziness',
          description: 'finding',
          laterality: null,
          notification_warning: null,
          snomedct: '404640003',
          health_service: [5, 4],
        },
        accompained_by: [
          {
            id: 24,
            name: 'flu',
            description: 'disorder',
            laterality: null,
            notification_warning: null,
            snomedct: '6142004',
            health_service: [5, 4],
          },
        ],
        pain_location: {
          id: 1,
          name: 'Around one eye or radiates one eye',
        },
        medications_related: [
          {
            id: 3,
            medication: {
              id: 13,
              name: 'aspirin',
            },
            prescribed_by: null,
            created_at: '2023-05-30T18:48:37.664396-05:00',
            updated_at: '2023-05-30T18:48:37.664397-05:00',
            medical_problems: [
              {
                id: 231,
                name_keyword: null,
              },
            ],
            status: 'A',
            providernote: 'asdsdfsdf',
            ordering_mode: '',
            earliestfilldate: null,
            refills_allowed: false,
            refills_quantity: null,
            ordering_quantity_value: null,
            with_reminder: false,
            ordering_quantity_unit: null,
            signetur: ' 2   by  route  for 23 WEEKS',
            goal: null,
          },
          {
            id: 1,
            medication: {
              id: 1,
              name: 'TylenoL',
            },
            prescribed_by: null,
            created_at: '2023-05-30T18:46:57.773307-05:00',
            updated_at: '2023-05-30T18:46:57.880717-05:00',
            medical_problems: [
              {
                id: 220,
                name_keyword: 'Radiant heat burn of skin',
              },
              {
                id: 261,
                name_keyword: null,
              },
            ],
            status: 'A',
            providernote: 'notes',
            ordering_mode: '',
            earliestfilldate: null,
            refills_allowed: false,
            refills_quantity: null,
            ordering_quantity_value: null,
            with_reminder: false,
            ordering_quantity_unit: null,
            signetur: ' 2   by  route  for 30 DAYS',
            goal: {
              id: 110,
              custom_title: null,
            },
          },
        ],
        created_at: '2023-06-08T11:17:57.137101-05:00',
        updated_at: '2023-06-20T16:04:49.119965-05:00',
        source: 'WEB',
        drug_effect_yn: true,
        pain_severity: 2,
        symptom_duration: 'everyday',
        reported_by_patient: false,
        patient_note: null,
        clinical_note: 'help',
        patient: 3,
        created_by: 6,
        updated_by: null,
      },
      cause: 'cizziness',
      cause_es: null,
      datetime_reading: '2023-06-08T16:26:48.298565-05:00',
      datetime_trigger_alert: '2023-06-08T16:26:48.298559-05:00',
      status: 'new',
      is_reviewed: false,
      is_read_by_patient: false,
      is_read_by_medical_staff: false,
      datetime_read_by_patient: '2023-06-08T16:26:48.298564-05:00',
      datetime_read_by_medical_staff: '2023-06-08T16:26:48.298565-05:00',
      symptom_report_yn: true,
      user: 6,
      transaction: null,
    },
    {
      id: 11044,
      category: {
        id: 5,
        name: 'Symptoms Report',
        name_es: 'Reporte de sintomas',
        description: 'Patient Symptoms report',
        description_es: 'Reportes para pacientes con sintomas',
      },
      patient: {
        id: 3,
        id_people: {
          id: 4,
          first_name: 'Joyce',
          last_name: 'Smither',
          date_of_birth: null,
          age: 32,
          gender: 'F',
          image: null,
          image_filename: null,
          email: 'mmralzate7@gmail.com',
          id_user: 8,
          cell_phone: '3136013550',
        },
      },
      prescription: null,
      normal_ranges: null,
      vital_sign: null,
      symptom_resport: {
        id: 6,
        symptoms: {
          id: 21,
          name: 'cizziness',
          description: 'finding',
          laterality: null,
          notification_warning: null,
          snomedct: '404640003',
          health_service: [5, 4],
        },
        accompained_by: [
          {
            id: 24,
            name: 'flu',
            description: 'disorder',
            laterality: null,
            notification_warning: null,
            snomedct: '6142004',
            health_service: [5, 4],
          },
        ],
        pain_location: {
          id: 1,
          name: 'Around one eye or radiates one eye',
        },
        medications_related: [
          {
            id: 3,
            medication: {
              id: 13,
              name: 'aspirin',
            },
            prescribed_by: null,
            created_at: '2023-05-30T18:48:37.664396-05:00',
            updated_at: '2023-05-30T18:48:37.664397-05:00',
            medical_problems: [
              {
                id: 231,
                name_keyword: null,
              },
            ],
            status: 'A',
            providernote: 'asdsdfsdf',
            ordering_mode: '',
            earliestfilldate: null,
            refills_allowed: false,
            refills_quantity: null,
            ordering_quantity_value: null,
            with_reminder: false,
            ordering_quantity_unit: null,
            signetur: ' 2   by  route  for 23 WEEKS',
            goal: null,
          },
          {
            id: 1,
            medication: {
              id: 1,
              name: 'TylenoL',
            },
            prescribed_by: null,
            created_at: '2023-05-30T18:46:57.773307-05:00',
            updated_at: '2023-05-30T18:46:57.880717-05:00',
            medical_problems: [
              {
                id: 220,
                name_keyword: 'Radiant heat burn of skin',
              },
              {
                id: 261,
                name_keyword: null,
              },
            ],
            status: 'A',
            providernote: 'notes',
            ordering_mode: '',
            earliestfilldate: null,
            refills_allowed: false,
            refills_quantity: null,
            ordering_quantity_value: null,
            with_reminder: false,
            ordering_quantity_unit: null,
            signetur: ' 2   by  route  for 30 DAYS',
            goal: {
              id: 110,
              custom_title: null,
            },
          },
        ],
        created_at: '2023-06-08T11:17:57.137101-05:00',
        updated_at: '2023-06-20T16:04:49.119965-05:00',
        source: 'WEB',
        drug_effect_yn: true,
        pain_severity: 2,
        symptom_duration: 'everyday',
        reported_by_patient: false,
        patient_note: null,
        clinical_note: 'help',
        patient: 3,
        created_by: 6,
        updated_by: null,
      },
      cause: 'cizziness',
      cause_es: null,
      datetime_reading: '2023-06-08T16:26:39.444095-05:00',
      datetime_trigger_alert: '2023-06-08T16:26:39.444089-05:00',
      status: 'new',
      is_reviewed: false,
      is_read_by_patient: false,
      is_read_by_medical_staff: false,
      datetime_read_by_patient: '2023-06-08T16:26:39.444095-05:00',
      datetime_read_by_medical_staff: '2023-06-08T16:26:39.444095-05:00',
      symptom_report_yn: true,
      user: 6,
      transaction: null,
    },
  ],
};

export default function NotificationsModel(data: []):
  | {
      data: [] | undefined;
    }
  | undefined {
  // // @ts-ignore
  data = dataAux;
  // console.log('MessagesModel: ', data);
  try {
    const result = data?.length ? data : [];
    return {
      data: result[0],
      // data: countUnreadMessages(result[0]),
    };
  } catch (e) {
    console.log('Error at NotificationsModel', e);
  }
}
