import { EwpLateralMenuItem } from '../../models/menu.ts';
import {
  ReportsIcon,
  TelehealthIcon,
  UserMdIcon,
  UsersGroupIcon,
} from '../../../../assets/icons';
import {
  Article,
  BarChart,
  DisplaySettings,
  DomainAdd,
  FlagCircle,
  GroupAdd,
  Inbox,
  LibraryBooks,
  LockPerson,
  MonitorHeart,
  PermPhoneMsg,
  Settings,
  Today,
} from '@mui/icons-material';
import React from 'react';

export const SETTINGS: EwpLateralMenuItem = {
  key: 4000,
  title: 'settings',
  link: '/settings',
  reload: false,
  icon: <Settings />,
  submenu: [
    {
      key: 4001,
      title: 'appointment_types',
      link: '/en/patients/#/appointments/types/',
      reload: true,
      icon: <Today />,
    },
    {
      key: 4002,
      title: 'care_team',
      link: '/en/physician/#/list/',
      reload: true,
      icon: <UserMdIcon />,
    },
    {
      key: 4003,
      title: 'consent_list',
      link: '/en/patients/#/consent/list',
      reload: true,
      icon: <LibraryBooks />,
    },
    {
      key: 4004,
      title: 'vitals_reference_ranges',
      link: '/en/patients/#/practice-settings',
      reload: true,
      icon: <MonitorHeart />,
    },
    {
      key: 4005,
      title: 'report_telehealth',
      link: '/en/clinic/telehealth/#/logs/list/',
      reload: true,
      icon: <TelehealthIcon />,
    },
    {
      key: 4006,
      title: 'population_groups',
      link: '/en/patients/#/population-groups',
      reload: true,
      icon: <UsersGroupIcon />,
    },
    {
      key: 4007,
      title: 'referring_provider_list',
      link: '/en/patients/#/referring-providers',
      reload: true,
      icon: <GroupAdd />,
    },
    {
      key: 4008,
      title: 'goal_set',
      link: '/en/patients/#/goal-set/list',
      reload: true,
      icon: <FlagCircle />,
    },
    {
      key: 4009,
      title: 'practice_list',
      link: '/en/settings/providers/#/list/',
      reload: true,
      icon: <Article />,
    },
    {
      key: 4010,
      title: 'fee_schedule',
      link: '/en/settings/providers/#/fee-schedule/',
      reload: true,
      icon: <Article />,
    },
    {
      key: 4011,
      title: 'insurances_list',
      link: '/en/settings/providers/#/insurances/list/',
      reload: true,
      icon: <Article />,
    },
    {
      key: 4012,
      title: 'voice_calls_report',
      link: '/en/patients/#/reports/voice-recording',
      reload: true,
      icon: <PermPhoneMsg />,
    },
    {
      key: 4013,
      title: 'new_provider',
      link: '/en/settings/providers/#/add/',
      reload: true,
      icon: <DomainAdd />,
    },
    {
      key: 4014,
      title: 'interoperability_settings',
      link: '/en/patients/#/interoperability/',
      reload: true,
      icon: <DisplaySettings />,
    },
    {
      key: 4015,
      title: 'admin_users',
      link: '/en/admin/users/',
      reload: true,
      icon: <LockPerson />,
    },
    {
      key: 4016,
      title: 'analytics_api_calls',
      link: '/en/patients/#/analyticsapicalls/',
      reload: true,
      icon: <BarChart />,
    },
    {
      key: 4017,
      title: 'reports_inbox',
      link: '/en/patients/#/reports/inbox',
      reload: true,
      icon: <Inbox />,
    },
    {
      key: 4018,
      title: 'reports_dashboard',
      link: '/en/patients/#/reports/dashboard',
      reload: true,
      icon: <ReportsIcon />,
    },
  ],
};
