// Api for Patient Search Section at Lateral Menu:
//esvyda-patients-api-patients-get
import { PatientSearchProps } from '../dto';
import { PatientSearchBoxProps } from '../dto/PatientSearchBox';

export const PATIENTS_SEARCH = [
  {
    total_patients: 163,
    patients: [
      {
        id: 60,
        height: 160.02,
        id_people: {
          id: 107,
          full_name: 'Alex, Ford',
          first_name: 'Ford',
          last_name: 'Alex',
          date_of_birth: '1996-05-07T00:00:00',
          cell_phone: '4094098456',
          home_phone: null,
          work_phone: null,
          street_address: '16887 Harries avenue',
          zip_code: '95008',
          title: null,
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: {
            id: 88,
            is_active: true,
            email: 'marcela.garcia256@esvyda.com',
          },
          age: 28,
          email: 'healthylifepbg14@gmail.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '3925',
          providergroupid: '22',
          providergroupname: '6 Hills Medical Associates',
          departmentid: '82',
          departmentname: '6 Hills',
        },
        emr_chart_id: null,
      },
      {
        id: 168,
        height: null,
        id_people: {
          id: 284,
          full_name: 'Amaru, Amaru',
          first_name: 'Amaru',
          last_name: 'Amaru',
          date_of_birth: '1981-01-28T00:00:00',
          cell_phone: '2233444444',
          home_phone: null,
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: null,
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: {
            id: 236,
            is_active: true,
            email: 'amaru@esvyda.com',
          },
          age: 44,
          email: 'amaru@esvyda.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6323',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '122',
          departmentname: 'Patient-facing name',
        },
        emr_chart_id: null,
      },
      {
        id: 191,
        height: null,
        id_people: {
          id: 423,
          full_name: 'Ana, Brown',
          first_name: 'Brown',
          last_name: 'Ana',
          date_of_birth: '1995-07-02T00:00:00',
          cell_phone: '232334343535',
          home_phone: '23435456666',
          work_phone: null,
          street_address: '232 Esther',
          zip_code: '98765',
          title: 'mrs',
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: {
            id: 278,
            is_active: true,
            email: 'tlemkec_p578n@umail2.com',
          },
          age: 29,
          email: 'tlemkec_p578n@umail2.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: 'Morgan Sarro',
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6364',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '150',
          departmentname: '7 Hills Department',
        },
        emr_chart_id: null,
      },
      {
        id: 34,
        height: null,
        id_people: {
          id: 78,
          full_name: 'Jones, Zack',
          first_name: 'Zack',
          last_name: 'Jones',
          date_of_birth: '1996-05-09T00:00:00',
          cell_phone: '4523688223',
          home_phone: '48825698',
          work_phone: '56248895',
          street_address: 'fajsjdhfiafif',
          zip_code: '95000',
          title: 'mr',
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: {
            id: 63,
            is_active: true,
            email: 'zackjones12@gmail.com',
          },
          age: 28,
          email: 'y.tatianaha@gmail.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {},
        emr_chart_id: null,
      },
      {
        id: 109,
        height: null,
        id_people: {
          id: 177,
          full_name: 'Kleist, Kristen',
          first_name: 'Kristen',
          last_name: 'Kleist',
          date_of_birth: '1989-04-17T00:00:00',
          cell_phone: null,
          home_phone: '5555907478',
          work_phone: null,
          street_address: 'New York',
          zip_code: '10001',
          title: 'mrs',
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: null,
          age: 35,
          email: 'user3849@athenahealth.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '1654',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '1',
          departmentname: 'Rome Office',
        },
        emr_chart_id: null,
      },
      {
        id: 106,
        height: 180.0,
        id_people: {
          id: 170,
          full_name: 'Kroeger, Jeff',
          first_name: 'Jeff',
          last_name: 'Kroeger',
          date_of_birth: '1992-05-23T00:00:00',
          cell_phone: '5555196003',
          home_phone: '5555922352',
          work_phone: null,
          street_address: '8762 Stoneridge Ct',
          zip_code: '04640',
          title: 'mr',
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: {
            id: 157,
            is_active: true,
            email: 'jeff@esvyda.com',
          },
          age: 32,
          email: 'user7128@athenahealth.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: '2018-04-20T23:25:00Z',
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '1635',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '21',
          departmentname: 'Cartersville Office',
        },
        emr_chart_id: null,
      },
      {
        id: 75,
        height: 185.0,
        id_people: {
          id: 127,
          full_name: 'LaBrie, James',
          first_name: 'James',
          last_name: 'LaBrie',
          date_of_birth: '1966-08-26T00:00:00',
          cell_phone: '4085796325',
          home_phone: '4086655774',
          work_phone: null,
          street_address: 'Los Gatos 458 Ave',
          zip_code: '12045',
          title: null,
          gender: 'M',
          image:
            'https://local-ewp-storage.s3.us-west-2.amazonaws.com/media/profile_photos/ec5decca5ed3d6b8079e2e7e7bacc9f2/db17eaa720a5cc62dfc4ef45244a91d1.png',
          image_filename: 'db17eaa720a5cc62dfc4ef45244a91d1.png',
          id_user: {
            id: 98,
            is_active: true,
            email: 'labrie@esvyda.com',
          },
          age: 58,
          email: null,
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: 'Morgan Sarro',
        transmission_date: '2018-10-09T00:09:10Z',
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6243',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '150',
          departmentname: '7 Hills Department',
        },
        emr_chart_id: null,
      },
      {
        id: 159,
        height: 154.94,
        id_people: {
          id: 266,
          full_name: 'Lee, Brandon',
          first_name: 'Brandon',
          last_name: 'Lee',
          date_of_birth: '1988-01-04T00:00:00',
          cell_phone: '4088443408',
          home_phone: '4088443408',
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: null,
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: {
            id: 218,
            is_active: true,
            email: 'bereicherung@tgiq9zwj6ttmq.tk',
          },
          age: 37,
          email: 'bereicherung@tgiq9zwj6ttmq.tk',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: 'Lufe Riño',
        transmission_date: '2018-11-29T18:06:24.690000Z',
        daily_review: null,
        athena_id: {},
        emr_chart_id: null,
      },
      {
        id: 72,
        height: 226.06,
        id_people: {
          id: 123,
          full_name: 'Leonardo, Decaprio',
          first_name: 'Decaprio',
          last_name: 'Leonardo',
          date_of_birth: '1977-09-28T00:00:00',
          cell_phone: '4098909871',
          home_phone: '4089098766',
          work_phone: '4098909872',
          street_address: '293 Esther',
          zip_code: '95008',
          title: null,
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: {
            id: 94,
            is_active: true,
            email: 'lios@gmail.com',
          },
          age: 47,
          email: 'leo@gmail.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: 'Lily Miller',
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '3944',
          providergroupid: '22',
          providergroupname: '6 Hills Medical Associates',
          departmentid: '82',
          departmentname: '6 Hills',
        },
        emr_chart_id: null,
      },
      {
        id: 80,
        height: 154.94,
        id_people: {
          id: 132,
          full_name: 'Linda, Roberts',
          first_name: 'Roberts',
          last_name: 'Linda',
          date_of_birth: '1990-08-31T00:00:00',
          cell_phone: '4098908793',
          home_phone: null,
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: null,
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: {
            id: 100,
            is_active: true,
            email: 'linda@esvyda.com',
          },
          age: 34,
          email: 'linda@esvyda.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: 'RCTEST TEST',
        transmission_date: '2017-07-06T14:29:54.154000Z',
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6245',
          providergroupid: '22',
          providergroupname: '6 Hills Medical Associates',
          departmentid: '82',
          departmentname: '6 Hills',
        },
        emr_chart_id: null,
      },
      {
        id: 96,
        height: 157.48,
        id_people: {
          id: 154,
          full_name: 'Linda, Sua',
          first_name: 'Sua',
          last_name: 'Linda',
          date_of_birth: '1979-07-15T00:00:00',
          cell_phone: '5678099877',
          home_phone: '5678099877',
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: 'mrs',
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: {
            id: 127,
            is_active: true,
            email: 'sua@esvyda.com',
          },
          age: 45,
          email: 'sue@esvyda.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: 'Lily Miller',
        transmission_date: '2019-01-15T17:52:04.264000Z',
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6252',
          providergroupid: '22',
          providergroupname: '6 Hills Medical Associates',
          departmentid: '82',
          departmentname: '6 Hills',
        },
        emr_chart_id: null,
      },
      {
        id: 90,
        height: 152.4,
        id_people: {
          id: 147,
          full_name: 'Lora, Barrios',
          first_name: 'Barrios',
          last_name: 'Lora',
          date_of_birth: '1961-02-25T00:00:00',
          cell_phone: '8908900765',
          home_phone: '8908900765',
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: null,
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: {
            id: 118,
            is_active: true,
            email: 'sube@esvyda.com',
          },
          age: 63,
          email: 'sube@esvyda.com',
          country_phone_code: '1',
        },
        pcp_title: 'mrs',
        pcp_full_name: 'Jessie Brown',
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6251',
          providergroupid: '22',
          providergroupname: '6 Hills Medical Associates',
          departmentid: '82',
          departmentname: '6 Hills',
        },
        emr_chart_id: null,
      },
      {
        id: 100,
        height: 157.48,
        id_people: {
          id: 161,
          full_name: 'Lori, Simpsons',
          first_name: 'Simpsons',
          last_name: 'Lori',
          date_of_birth: '2000-05-10T00:00:00',
          cell_phone: '2093838377',
          home_phone: null,
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: null,
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: {
            id: 138,
            is_active: true,
            email: 'lori@esvyda.com',
          },
          age: 24,
          email: 'lori@esvyda.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: '2017-12-11T13:13:33Z',
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6325',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '150',
          departmentname: '7 Hills Department',
        },
        emr_chart_id: null,
      },
      {
        id: 6,
        height: 167.64,
        id_people: {
          id: 17,
          full_name: 'Lozano, Elias',
          first_name: 'Elias',
          last_name: 'Lozano',
          date_of_birth: '1965-09-27T00:00:00',
          cell_phone: '4088290985',
          home_phone: '',
          work_phone: null,
          street_address: null,
          zip_code: '95008',
          title: 'mr',
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: {
            id: 15,
            is_active: true,
            email: 'lozano@esvyda.com',
          },
          age: 59,
          email: 'colombiano3565@gmail.com',
          country_phone_code: '1',
        },
        pcp_title: 'mr',
        pcp_full_name: 'Epocrates Patient Five',
        transmission_date: '2017-10-02T15:23:07.127000Z',
        daily_review: null,
        athena_id: {},
        emr_chart_id: null,
      },
      {
        id: 117,
        height: 149.86,
        id_people: {
          id: 196,
          full_name: 'Lozano, Elim',
          first_name: 'Elim',
          last_name: 'Lozano',
          date_of_birth: '2000-10-24T00:00:00',
          cell_phone: '4082223333',
          home_phone: null,
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: 'mr',
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: null,
          age: 24,
          email: 'elimjazziel8@gmail.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {},
        emr_chart_id: null,
      },
      {
        id: 91,
        height: 178.0,
        id_people: {
          id: 149,
          full_name: 'Lozano, Romulo',
          first_name: 'Romulo',
          last_name: 'Lozano',
          date_of_birth: '1950-01-01T00:00:00',
          cell_phone: '4088360951',
          home_phone: null,
          work_phone: null,
          street_address: '1512 almaden expressway',
          zip_code: '95128',
          title: 'mr',
          gender: 'M',
          image:
            'https://local-ewp-storage.s3.us-west-2.amazonaws.com/media/profile_photos/f2217062e9a397a1dca429e7d70bc6ca/98b9236a46e406ff5dade95c0f06f855.png',
          image_filename: '98b9236a46e406ff5dade95c0f06f855.png',
          id_user: {
            id: 120,
            is_active: true,
            email: 'rlozano@esvyda.com',
          },
          age: 75,
          email: 'rlozano@esvyda.com',
          country_phone_code: '1',
        },
        pcp_title: 'mr',
        pcp_full_name: 'Epocrates Patient Five',
        transmission_date: '2017-10-20T02:54:27.845000Z',
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6334',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '150',
          departmentname: '7 Hills Department',
        },
        emr_chart_id: null,
      },
      {
        id: 118,
        height: 149.86,
        id_people: {
          id: 197,
          full_name: 'Lozano, Sahyii',
          first_name: 'Sahyii',
          last_name: 'Lozano',
          date_of_birth: '1999-04-23T00:00:00',
          cell_phone: '4082345678',
          home_phone: null,
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: 'ms',
          gender: 'F',
          image:
            'https://local-ewp-storage.s3.us-west-2.amazonaws.com/media/profile_photos/85d8ce590ad8981ca2c8286f79f59954/382b83b3473cfdf07a11dc3368398355.png',
          image_filename: '382b83b3473cfdf07a11dc3368398355.png',
          id_user: {
            id: 155,
            is_active: true,
            email: 'ymeli2002@gmail.com',
          },
          age: 25,
          email: 'ymeli2002@gmail.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: '2018-04-05T22:56:40Z',
        daily_review: null,
        athena_id: {},
        emr_chart_id: null,
      },
      {
        id: 37,
        height: null,
        id_people: {
          id: 81,
          full_name: 'Luna, Andy',
          first_name: 'Andy',
          last_name: 'Luna',
          date_of_birth: '1990-01-01T00:00:00',
          cell_phone: null,
          home_phone: null,
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: 'mrs',
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: null,
          age: 35,
          email: null,
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {},
        emr_chart_id: null,
      },
      {
        id: 134,
        height: null,
        id_people: {
          id: 226,
          full_name: 'Marconi, Neida',
          first_name: 'Neida',
          last_name: 'Marconi',
          date_of_birth: '1991-06-18T00:00:00',
          cell_phone: '5555282319',
          home_phone: '5555888933',
          work_phone: null,
          street_address: '8762 Stoneridge Ct',
          zip_code: '04787',
          title: 'mrs',
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: {
            id: 180,
            is_active: true,
            email: 'client5997@athenahealth.com',
          },
          age: 33,
          email: 'client5997@athenahealth.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '5997',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '1',
          departmentname: 'Rome Office',
        },
        emr_chart_id: null,
      },
      {
        id: 68,
        height: 274.32,
        id_people: {
          id: 115,
          full_name: 'Marie, Curie',
          first_name: 'Curie',
          last_name: 'Marie',
          date_of_birth: '1980-01-30T00:00:00',
          cell_phone: '4098790982',
          home_phone: '4098790982',
          work_phone: null,
          street_address: null,
          zip_code: '09089',
          title: null,
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: {
            id: 89,
            is_active: true,
            email: 'marie@esvyda.com',
          },
          age: 45,
          email: 'lora@gmail.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: 'Lily Miller',
        transmission_date: '2018-12-17T22:18:00Z',
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '3941',
          providergroupid: '22',
          providergroupname: '6 Hills Medical Associates',
          departmentid: '82',
          departmentname: '6 Hills',
        },
        emr_chart_id: null,
      },
      {
        id: 70,
        height: 274.32,
        id_people: {
          id: 121,
          full_name: 'Mark, Mark',
          first_name: 'Mark',
          last_name: 'Mark',
          date_of_birth: '1970-03-07T00:00:00',
          cell_phone: '2390049948',
          home_phone: null,
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: null,
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: null,
          age: 54,
          email: 'marck@gmail.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {},
        emr_chart_id: null,
      },
      {
        id: 77,
        height: null,
        id_people: {
          id: 129,
          full_name: 'Mary, Morrison',
          first_name: 'Morrison',
          last_name: 'Mary',
          date_of_birth: '1978-12-05T00:00:00',
          cell_phone: '9089786098',
          home_phone: null,
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: null,
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: {
            id: 99,
            is_active: true,
            email: 'marcelaght@esvyda.com',
          },
          age: 46,
          email: 'marry@esvyda.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {},
        emr_chart_id: null,
      },
      {
        id: 18,
        height: 165.0,
        id_people: {
          id: 39,
          full_name: 'Mc Bride, Alissa',
          first_name: 'Alissa',
          last_name: 'Mc Bride',
          date_of_birth: '1994-05-19T00:00:00',
          cell_phone: '3597255486',
          home_phone: '3598655667',
          work_phone: null,
          street_address: 'Jacksonville 234 Ave',
          zip_code: null,
          title: 'mrs',
          gender: 'F',
          image:
            'https://local-ewp-storage.s3.us-west-2.amazonaws.com/media/profile_photos/d67d8ab4f4c10bf22aa353e27879133c/3695dcff5673c5a6f9e78c6ff602938e.png',
          image_filename: '3695dcff5673c5a6f9e78c6ff602938e.png',
          id_user: {
            id: 53,
            is_active: true,
            email: 'amcbride@esvyda.com',
          },
          age: 30,
          email: null,
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: 'Morgan Sarro',
        transmission_date: '2019-05-29T22:36:56Z',
        daily_review: null,
        athena_id: {},
        emr_chart_id: null,
      },
      {
        id: 87,
        height: 180.0,
        id_people: {
          id: 142,
          full_name: 'McQuade, Joya',
          first_name: 'Joya',
          last_name: 'McQuade',
          date_of_birth: '1978-08-23T00:00:00',
          cell_phone: '',
          home_phone: '5805648529',
          work_phone: '',
          street_address: '8762 Stoneridge Ct',
          zip_code: '04084',
          title: 'mrs',
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: null,
          age: 46,
          email: 'client487@athenahealth.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '487',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '1',
          departmentname: 'Rome Office',
        },
        emr_chart_id: null,
      },
      {
        id: 130,
        height: 162.56,
        id_people: {
          id: 219,
          full_name: 'Meaney, Ivory',
          first_name: 'Ivory',
          last_name: 'Meaney',
          date_of_birth: '1928-05-24T00:00:00',
          cell_phone: '5555500830',
          home_phone: '5555878966',
          work_phone: null,
          street_address: 'Cra 3 Bis 32b 57',
          zip_code: '12005',
          title: 'mr',
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: {
            id: 172,
            is_active: true,
            email: 'ivory@esvyda.com',
          },
          age: 96,
          email: 'damurillo@utp.edu.co',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: 'Dan Pato',
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '2545',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '1',
          departmentname: 'Rome Office',
        },
        emr_chart_id: null,
      },
      {
        id: 122,
        height: null,
        id_people: {
          id: 203,
          full_name: 'Mejias, Edythe',
          first_name: 'Edythe',
          last_name: 'Mejias',
          date_of_birth: '1989-10-12T00:00:00',
          cell_phone: '5555880195',
          home_phone: '5555020717',
          work_phone: null,
          street_address: '8762 Stoneridge Ct',
          zip_code: '30083',
          title: 'mrs',
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: null,
          age: 35,
          email: 'client5754@athenahealth.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '5754',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '1',
          departmentname: 'Rome Office',
        },
        emr_chart_id: null,
      },
      {
        id: 67,
        height: 142.24,
        id_people: {
          id: 114,
          full_name: 'Middleton, Elina',
          first_name: 'Elina',
          last_name: 'Middleton',
          date_of_birth: '1989-01-26T00:00:00',
          cell_phone: '5555912188',
          home_phone: '5555344740',
          work_phone: '8885557656',
          street_address: '8762 Stoneridge Ct',
          zip_code: '31156',
          title: 'mr',
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: {
            id: 85,
            is_active: true,
            email: 'user23811@athenahealth.com',
          },
          age: 36,
          email: 'user20013@athenahealth.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: '2017-03-22T23:28:20.224000Z',
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '3931',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '1',
          departmentname: 'Rome Office',
        },
        emr_chart_id: null,
      },
      {
        id: 40,
        height: null,
        id_people: {
          id: 86,
          full_name: 'Miller, Andrew',
          first_name: 'Andrew',
          last_name: 'Miller',
          date_of_birth: '1990-05-05T00:00:00',
          cell_phone: null,
          home_phone: '408 808 5230',
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: 'mr',
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: null,
          age: 34,
          email: null,
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {},
        emr_chart_id: null,
      },
      {
        id: 165,
        height: 157.48,
        id_people: {
          id: 281,
          full_name: 'Miranda, Miro',
          first_name: 'Miro',
          last_name: 'Miranda',
          date_of_birth: '2018-12-03T00:00:00',
          cell_phone: '4509876654',
          home_phone: '4509876654',
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: null,
          gender: 'I',
          image: null,
          image_filename: null,
          id_user: {
            id: 234,
            is_active: true,
            email: 'miranda@esvyda.com',
          },
          age: 6,
          email: 'miranda@esvyda.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6327',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '150',
          departmentname: '7 Hills Department',
        },
        emr_chart_id: null,
      },
      {
        id: 166,
        height: null,
        id_people: {
          id: 282,
          full_name: 'Mirta, Diaz',
          first_name: 'Diaz',
          last_name: 'Mirta',
          date_of_birth: '2001-01-08T00:00:00',
          cell_phone: '2323234434',
          home_phone: null,
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: null,
          gender: 'I',
          image: null,
          image_filename: null,
          id_user: {
            id: 235,
            is_active: true,
            email: 'mirta@esvyda.com',
          },
          age: 24,
          email: 'mirta@esvyda.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6324',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '150',
          departmentname: '7 Hills Department',
        },
        emr_chart_id: null,
      },
      {
        id: 206,
        height: null,
        id_people: {
          id: 443,
          full_name: 'Momoa, Jason',
          first_name: 'Jason',
          last_name: 'Momoa',
          date_of_birth: '1995-08-11T00:00:00',
          cell_phone: '2334345566',
          home_phone: '2334345566',
          work_phone: null,
          street_address: '2343',
          zip_code: '34567',
          title: 'mr',
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: {
            id: 297,
            is_active: true,
            email: 'sharrisw_b526u@umail2.com',
          },
          age: 29,
          email: 'sharrisw_b526u@umail2.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: 'Morgan Sarro',
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6365',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '150',
          departmentname: '7 Hills Department',
        },
        emr_chart_id: null,
      },
      {
        id: 151,
        height: 172.0,
        id_people: {
          id: 254,
          full_name: 'Montoya, Andres',
          first_name: 'Andres',
          last_name: 'Montoya',
          date_of_birth: '1990-12-28T00:00:00',
          cell_phone: '9397757565',
          home_phone: null,
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: 'mr',
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: {
            id: 206,
            is_active: true,
            email: 'amontoya@esvyda.com',
          },
          age: 34,
          email: 'amontoya@esvyda.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {},
        emr_chart_id: null,
      },
      {
        id: 47,
        height: 208.28,
        id_people: {
          id: 94,
          full_name: 'Sample, Patient',
          first_name: 'Patient',
          last_name: 'Sample',
          date_of_birth: '1995-06-12T00:00:00',
          cell_phone: '3136013550',
          home_phone: '3136013550',
          work_phone: '3059166317',
          street_address: null,
          zip_code: null,
          title: null,
          gender: 'F',
          image:
            'https://local-ewp-storage.s3.us-west-2.amazonaws.com/media/profile_photos/f4b9ec30ad9f68f89b29639786cb62ef/f5ebdb42c05fe841573a982f6b81ded0.png',
          image_filename: 'f5ebdb42c05fe841573a982f6b81ded0.png',
          id_user: {
            id: 70,
            is_active: true,
            email: 'patientsample@esvyda.com',
          },
          age: 29,
          email: 'healthylifepbg14@gmail.com',
          country_phone_code: '57',
        },
        pcp_title: null,
        pcp_full_name: 'lala lala',
        transmission_date: '2026-11-19T23:38:00Z',
        daily_review: null,
        athena_id: {},
        emr_chart_id: null,
      },
      {
        id: 186,
        height: null,
        id_people: {
          id: 418,
          full_name: 'Samus, Saran',
          first_name: 'Saran',
          last_name: 'Samus',
          date_of_birth: '2019-06-07T00:00:00',
          cell_phone: null,
          home_phone: null,
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: 'mrs',
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: null,
          age: 5,
          email: 'invalidemail@esvyda.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: 'Morgan Sarro',
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6361',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '150',
          departmentname: '7 Hills Department',
        },
        emr_chart_id: null,
      },
      {
        id: 155,
        height: 157.48,
        id_people: {
          id: 258,
          full_name: 'Sandra, Velez',
          first_name: 'Velez',
          last_name: 'Sandra',
          date_of_birth: '1995-02-02T00:00:00',
          cell_phone: '4098907890',
          home_phone: null,
          work_phone: '4098907890',
          street_address: 'road',
          zip_code: '98009',
          title: null,
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: {
            id: 210,
            is_active: true,
            email: 'sandra@esvyda.com',
          },
          age: 30,
          email: 'pgalindo@sahlimtechnologies.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: 'Lily Miller',
        transmission_date: '2019-01-14T18:13:32.239000Z',
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6335',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '150',
          departmentname: '7 Hills Department',
        },
        emr_chart_id: null,
      },
      {
        id: 52,
        height: 190.0,
        id_people: {
          id: 99,
          full_name: 'Sara, Bright',
          first_name: 'Bright',
          last_name: 'Sara',
          date_of_birth: '1975-12-29T00:00:00',
          cell_phone: '1111111111',
          home_phone: null,
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: null,
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: null,
          age: 49,
          email: 'healthylifepbg14@gmail.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {},
        emr_chart_id: null,
      },
      {
        id: 193,
        height: null,
        id_people: {
          id: 426,
          full_name: 'Sea, Sea',
          first_name: 'Sea',
          last_name: 'Sea',
          date_of_birth: '2000-07-02T00:00:00',
          cell_phone: '3456789887',
          home_phone: '3456789887',
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: 'mrs',
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: {
            id: 281,
            is_active: true,
            email: 'veum.kaylaf_k917e@vcbox.pro',
          },
          age: 24,
          email: 'veum.kaylaf_k917e@vcbox.pro',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6367',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '150',
          departmentname: '7 Hills Department',
        },
        emr_chart_id: null,
      },
      {
        id: 86,
        height: null,
        id_people: {
          id: 141,
          full_name: 'Shy, Louetta',
          first_name: 'Louetta',
          last_name: 'Shy',
          date_of_birth: '1989-09-27T00:00:00',
          cell_phone: '5555088446',
          home_phone: '5555371647',
          work_phone: null,
          street_address: '8762 Stoneridge Ct',
          zip_code: '01007',
          title: 'mrs',
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: null,
          age: 35,
          email: 'user23811@athenahealth.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '1153',
          providergroupid: '22',
          providergroupname: '6 Hills Medical Associates',
          departmentid: '82',
          departmentname: '6 Hills',
        },
        emr_chart_id: null,
      },
      {
        id: 85,
        height: null,
        id_people: {
          id: 140,
          full_name: 'Shy, Louetta',
          first_name: 'Louetta',
          last_name: 'Shy',
          date_of_birth: '1989-09-27T00:00:00',
          cell_phone: '5555088446',
          home_phone: '5555371647',
          work_phone: null,
          street_address: '8762 Stoneridge Ct',
          zip_code: '01007',
          title: 'mrs',
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: null,
          age: 35,
          email: 'user23811@athenahealth.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '1159',
          providergroupid: '22',
          providergroupname: '6 Hills Medical Associates',
          departmentid: '82',
          departmentname: '6 Hills',
        },
        emr_chart_id: null,
      },
      {
        id: 178,
        height: 170.0,
        id_people: {
          id: 410,
          full_name: 'Silva, Andresson',
          first_name: 'Andresson',
          last_name: 'Silva',
          date_of_birth: '2009-05-12T00:00:00',
          cell_phone: '4082003040',
          home_phone: null,
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: 'mr',
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: {
            id: 273,
            is_active: true,
            email: 'camf.651@gmail.com',
          },
          age: 15,
          email: 'camf.651@gmail.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {},
        emr_chart_id: null,
      },
      {
        id: 167,
        height: 142.24,
        id_people: {
          id: 283,
          full_name: 'Simpson, Lisa',
          first_name: 'Lisa',
          last_name: 'Simpson',
          date_of_birth: '1981-02-04T00:00:00',
          cell_phone: '4869897644',
          home_phone: '4087665443',
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: null,
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: null,
          age: 44,
          email: 'lisa@esvyda.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6326',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '150',
          departmentname: '7 Hills Department',
        },
        emr_chart_id: null,
      },
      {
        id: 170,
        height: null,
        id_people: {
          id: 286,
          full_name: 'Simpsons, Bart',
          first_name: 'Bart',
          last_name: 'Simpsons',
          date_of_birth: '1981-02-14T00:00:00',
          cell_phone: '7122334556',
          home_phone: null,
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: null,
          gender: 'I',
          image: null,
          image_filename: null,
          id_user: {
            id: 238,
            is_active: true,
            email: 'bart@esvyda.com',
          },
          age: 43,
          email: 'bart@esvyda.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6339',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '150',
          departmentname: '7 Hills Department',
        },
        emr_chart_id: null,
      },
      {
        id: 169,
        height: null,
        id_people: {
          id: 285,
          full_name: 'Simpsons, March',
          first_name: 'March',
          last_name: 'Simpsons',
          date_of_birth: '2002-04-02T00:00:00',
          cell_phone: '2543456788',
          home_phone: null,
          work_phone: null,
          street_address: null,
          zip_code: null,
          title: null,
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: {
            id: 237,
            is_active: true,
            email: 'march@esvyda.com',
          },
          age: 22,
          email: 'march@esvyda.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6338',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '150',
          departmentname: '7 Hills Department',
        },
        emr_chart_id: null,
      },
      {
        id: 190,
        height: null,
        id_people: {
          id: 422,
          full_name: 'Smith, Adam',
          first_name: 'Adam',
          last_name: 'Smith',
          date_of_birth: '1978-07-03T00:00:00',
          cell_phone: '5467787998',
          home_phone: '2334345566',
          work_phone: null,
          street_address: '234 Esther',
          zip_code: '98766',
          title: 'mr',
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: {
            id: 277,
            is_active: true,
            email: 'nonehabon@fast-email.info',
          },
          age: 46,
          email: 'nonehabon@fast-email.info',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: 'Morgan Sarro',
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '6363',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '150',
          departmentname: '7 Hills Department',
        },
        emr_chart_id: null,
      },
      {
        id: 102,
        height: null,
        id_people: {
          id: 164,
          full_name: 'Smith, Adan',
          first_name: 'Adan',
          last_name: 'Smith',
          date_of_birth: '1969-11-28T00:00:00',
          cell_phone: '2164641321',
          home_phone: '2354546856',
          work_phone: '2322545411',
          street_address: '8762 Stoneridge Ct',
          zip_code: '01806',
          title: 'mr',
          gender: 'M',
          image:
            'https://local-ewp-storage.s3.us-west-2.amazonaws.com/media/profile_photos/fa7cdfad1a5aaf8370ebeda47a1ff1c3/a6cfffa428185a13c56b692d110c4273.png',
          image_filename: 'a6cfffa428185a13c56b692d110c4273.png',
          id_user: null,
          age: 55,
          email: 'darwin.367@hotmail.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: '2018-04-20T20:45:00Z',
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '3446',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '150',
          departmentname: '7 Hills Department',
        },
        emr_chart_id: null,
      },
      {
        id: 107,
        height: null,
        id_people: {
          id: 172,
          full_name: 'Smith, Barton',
          first_name: 'Barton',
          last_name: 'Smith',
          date_of_birth: '1991-03-22T00:00:00',
          cell_phone: '452512322',
          home_phone: '452512322',
          work_phone: null,
          street_address: '8762 Stoneridge Ct',
          zip_code: '36040',
          title: 'mr',
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: null,
          age: 33,
          email: 'client296@athenahealth.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: '2018-04-28T01:16:00Z',
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '296',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '1',
          departmentname: 'Rome Office',
        },
        emr_chart_id: null,
      },
      {
        id: 103,
        height: null,
        id_people: {
          id: 166,
          full_name: 'Smith, Joe',
          first_name: 'Joe',
          last_name: 'Smith',
          date_of_birth: '2015-03-29T00:00:00',
          cell_phone: '5555923803',
          home_phone: '5555810803',
          work_phone: null,
          street_address: 'Newyork',
          zip_code: '10001',
          title: 'mr',
          gender: 'M',
          image: null,
          image_filename: null,
          id_user: null,
          age: 9,
          email: 'user22592@athenahealth.com',
          country_phone_code: '1',
        },
        pcp_title: null,
        pcp_full_name: null,
        transmission_date: '2018-04-27T19:45:00Z',
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '5748',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '1',
          departmentname: 'Rome Office',
        },
        emr_chart_id: null,
      },
      {
        id: 144,
        height: null,
        id_people: {
          id: 237,
          full_name: 'Smith, Marvis',
          first_name: 'Marvis',
          last_name: 'Smith',
          date_of_birth: '1957-05-15T00:00:00',
          cell_phone: null,
          home_phone: '5555942879',
          work_phone: null,
          street_address: '8762 Stoneridge Ct',
          zip_code: '01806',
          title: 'mrs',
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: {
            id: 189,
            is_active: true,
            email: 'marvis@esvyda.com',
          },
          age: 67,
          email: 'marvis@esvyda.com',
          country_phone_code: '1',
        },
        pcp_title: 'mr',
        pcp_full_name: 'Epocrates Patient Five',
        transmission_date: null,
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '472',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '21',
          departmentname: 'Cartersville Office',
        },
        emr_chart_id: null,
      },
      {
        id: 3,
        height: 177.8,
        id_people: {
          id: 4,
          full_name: 'Smither, Joyce',
          first_name: 'Joyce',
          last_name: 'Smither',
          date_of_birth: '1992-06-15T00:00:00',
          cell_phone: '3136013550',
          home_phone: '3136013596',
          work_phone: '3136013591',
          street_address: 'Road',
          zip_code: '98009',
          title: 'mrs',
          gender: 'F',
          image: null,
          image_filename: null,
          id_user: {
            id: 8,
            is_active: true,
            email: 'mmralzate7@gmail.com',
          },
          age: 32,
          email: 'mmralzate7@gmail.com',
          country_phone_code: '57',
        },
        pcp_title: 'mr',
        pcp_full_name: 'Joel Obeso',
        transmission_date: '2024-05-16T20:11:52Z',
        daily_review: null,
        athena_id: {
          practiceid: '1959008',
          practiceidewp: 2,
          id: '3921',
          providergroupid: '1',
          providergroupname: '7 Hills Medical Group',
          departmentid: '150',
          departmentname: '7 Hills Department',
        },
        emr_chart_id: '1234780',
      },
    ],
  },
];

export default function PatientSearchAdapter(data: PatientSearchProps) {
  const patients = data;
  return {
    totalPatients: patients.total_patients,
    patients: patients.map((patient) => ({
      patientId: patient.id,
      patientFirstName: patient.id_people.first_name,
      patientLastName: patient.id_people.last_name,
      patientFullName: patient.id_people.full_name,
      patientDOB: patient.id_people.date_of_birth,
      patientStatus: patient.id_people.id_user?.is_active || null,
    })),
  };
}

export function searchBoxAdapter(data: PatientSearchBoxProps) {
  const searchData = data;
  return {
    searchBox: searchData.search_box,
    dailyReview: searchData.daily_review,
    section: searchData.section,
    departmentInsertions: searchData.department_insertions,
  };
}
