// Api for Patient Search Section at Lateral Menu:
//esvyda-interoperability-search-patient-departments

import { ProviderDepartmentsProps } from '../dto';

export const PROVIDER_DEPARTMENTS = [
  {
    message: [
      {
        id: 5,
        departmentid: '82',
        patientdepartmentname: '6 Hills',
        providergroupid: '22',
        providergroupname: '6 Hills Medical Associates',
        practice: 2,
      },
      {
        id: 15,
        departmentid: '150',
        patientdepartmentname: '7 Hills Department',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 22,
        departmentid: '163',
        patientdepartmentname: 'athenaHealth',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 20,
        departmentid: '161',
        patientdepartmentname: 'West Branch',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 13,
        departmentid: '148',
        patientdepartmentname:
          'Patient Face Name Test Department 47 College St',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 2,
        departmentid: '21',
        patientdepartmentname: 'Cartersville Office',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 4,
        departmentid: '62',
        patientdepartmentname: 'Blackstone Valley',
        providergroupid: '2',
        providergroupname: 'BLACKSTONE VALLEY MEDICAL GROUP',
        practice: 2,
      },
      {
        id: 1,
        departmentid: '1',
        patientdepartmentname: 'Rome Office',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 85,
        departmentid: '165',
        patientdepartmentname: 'test',
        providergroupid: '22',
        providergroupname: '6 Hills Medical Associates',
        practice: 2,
      },
      {
        id: 23,
        departmentid: '164',
        patientdepartmentname: 'Internal Medical Associates',
        providergroupid: '2',
        providergroupname: 'BLACKSTONE VALLEY MEDICAL GROUP',
        practice: 2,
      },
      {
        id: 90,
        departmentid: '171',
        patientdepartmentname: 'FL Dept',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 89,
        departmentid: '170',
        patientdepartmentname: 'athenaclinic',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 87,
        departmentid: '168',
        patientdepartmentname: 'Springfield Medical',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 86,
        departmentid: '166',
        patientdepartmentname: 'Training Dept Patient Facing Name',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 21,
        departmentid: '162',
        patientdepartmentname: 'Main Office',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 19,
        departmentid: '160',
        patientdepartmentname: 'Heisman Office',
        providergroupid: '22',
        providergroupname: '6 Hills Medical Associates',
        practice: 2,
      },
      {
        id: 88,
        departmentid: '169',
        patientdepartmentname: '16.11 Testing',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 18,
        departmentid: '159',
        patientdepartmentname: 'Lombardi Office',
        providergroupid: '22',
        providergroupname: '6 Hills Medical Associates',
        practice: 2,
      },
      {
        id: 17,
        departmentid: '157',
        patientdepartmentname: 'CommOpsDevTest',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 16,
        departmentid: '155',
        patientdepartmentname: 'kate DEPT',
        providergroupid: '62',
        providergroupname: 'kate PG',
        practice: 2,
      },
      {
        id: 14,
        departmentid: '149',
        patientdepartmentname: 'Psych OP',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 12,
        departmentid: '147',
        patientdepartmentname:
          'Ohio Health Primary Care Pickerington Office 1234',
        providergroupid: '42',
        providergroupname: '5 Peaks Medical Organization',
        practice: 2,
      },
      {
        id: 11,
        departmentid: '145',
        patientdepartmentname: 'Belfast',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 10,
        departmentid: '144',
        patientdepartmentname: 'NonCommunicator',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 9,
        departmentid: '143',
        patientdepartmentname: '5 Peaks',
        providergroupid: '42',
        providergroupname: '5 Peaks Medical Organization',
        practice: 2,
      },
      {
        id: 8,
        departmentid: '142',
        patientdepartmentname:
          'Patient Face Name Test Department 47 College St',
        providergroupid: '2',
        providergroupname: 'BLACKSTONE VALLEY MEDICAL GROUP',
        practice: 2,
      },
      {
        id: 7,
        departmentid: '122',
        patientdepartmentname: 'Patient-facing name',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 6,
        departmentid: '102',
        patientdepartmentname: 'Cardiology Consults',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
      {
        id: 3,
        departmentid: '42',
        patientdepartmentname: 'Commerce Medical Group',
        providergroupid: '1',
        providergroupname: '7 Hills Medical Group',
        practice: 2,
      },
    ],
  },
];

export default function ProviderDepartmentAdapter(
  data: ProviderDepartmentsProps
) {
  const departments = data[0];
  return {
    departments: departments.message.map((department) => ({
      id: department.id,
      departmentId: department.departmentid,
      departmentName: department.patientdepartmentname,
      departmentPractice: department.practice,
      providerGroupId: department.providergroupid,
      providerGroupName: department.providergroupname,
    })),
  };
}
